### ISSUE TITLE
Current API Disscussion

### ISSUE THREAD

**Issue by paul-ruth** [fabric-testbed/jupyter-examples#103]
Just a list of things to discuss at the meeting:

- Regular getters/setters on topology all objects and discourage users for accessing the attributes directly. 
- Revisit the capacity settings.  I'm still not convinced the capacities are special from the perspective of the user.  It would be way more straight forward to have three sets of getters/setters, one for each of the capacities.
- topology.nodes is a list of node names (not nodes) then you use the node names to pull nodes of the list of nodes that is also called topology.nodes.  I think there should just be a topology.get_nodes() getter that returns a list of nodes.  
- Each topology object can a have a "tojson" that returns raw json if you want to use it that way.  The method that does this should be explicitly coded by us and should always return valid json even if we need do something difficult to make it happen.  
- What is the purpose of the slice manager calls to get slivers and sliver status if that info is all in the topology?

**Comment by kthare10** [comment]
Fablib API was written on top on low level APIs exposed by Control Framework.
