### ISSUE TITLE
Exceptions vs return codes

### ISSUE THREAD

**Issue by paul-ruth** [fabric-testbed/jupyter-examples#115]
I think the API should just raise exceptions instead of having return codes.  

- Reusing the return value for errors and valid returned objects makes it difficult to use the calls in your application because the type of object that a variable is pointing could be different upon a failed API call.  Eventually, you get an exception anyway when you try to use the returned object.  The problem is that the exception is  not at the source of the failure and doesn't contain the info about why it failed.
- It also makes it more complicated to write an application b/c you need to both check the return code AND catch exceptions because there are other exceptions thrown.

**Comment by kthare10** [comment]
Fablib API has been written on top of Control Framework which addresses the concerns listed above.
https://pypi.org/project/fabrictestbed-extensions/
