### ISSUE TITLE
network_service.add_interface

### ISSUE THREAD

**Issue by paul-ruth** [fabric-testbed/jupyter-examples#119]
We need a way to add/remove interfaces from existing network services.

this should work in the same way that adding/remove in other resources works.  i.e.:

my_network_sericve.add_interface(my_node.interface_list[0])

**Comment by ibaldin** [comment]
There is already the ability to remove an interface from service:

https://github.com/fabric-testbed/InformationModel/blob/6f01e208b2cf5f8b721d16a48e4df97ce0b727bc/fim/user/network_service.py#L269

1. This is how it is today, except that we do not have slice modify
2. This is how it works today - you first define the nodes, then network services with specific interfaces of those nodes. You can also remove interfaces from service using ns.disconnect_interface() call. Adding more interfaces beyond what is defined in the constructor will be done when we have slice modify functionality.

**Comment by paul-ruth** [comment]
Right above the "disconnect_interface" function is "__connect_interface" (https://github.com/fabric-testbed/InformationModel/blob/6f01e208b2cf5f8b721d16a48e4df97ce0b727bc/fim/user/network_service.py#L239)

Is there a reason why it is private or can we make it public?

**Comment by paul-ruth** [comment]
So, the validation needs to be done before the request is submitted not while the request is being built.  It should be perfectly fine to have request that is being built and is not in a valid state.   Keep in mind that even though this is a declarative model it is being built by procedural code.

**Comment by paul-ruth** [comment]
What makes more sense in the absence of modify? I don't see how modify changes anything about when the request must be in a valid state.

**Comment by ibaldin** [comment]
If you can only create services as one shot and cannot modify them, it makes more sense not to have APIs that modify them for the moment.
