### ISSUE TITLE
Forum login workflow

### ISSUE THREAD

**Issue by paul-ruth** [fabric-testbed/jupyter-examples#131]
Users are having problems figuring out how to log into the forums.  The problem is the login id/password fields that at the bottom of the forums that doesn't work.

We need to remove the non-functioning login widgets and add a link that goes straight to the OpenID login.

**Comment by ibaldin** [comment]
I don't think we have a choice but to ask Yaxue or Michael hack WordPress PHP here. We should discuss next Monday - I can see this is a pain point that needs to be fixed.
