### ISSUE TITLE
Capacities and Instance types

### ISSUE THREAD

**Issue by paul-ruth** [fabric-testbed/jupyter-examples#139]
Setting capacities that get rounded in extreme ways is a bit confusing and results is unexpected results.  

As it is currently deployed , it is not very useful because cores and ram are always 1:4 so you can't create memory heavy node or cpu heavy nodes.  The rounding that is needed to step up to the 1:4 ratio can be unexpected.

Ultimately OpenStack uses an instance type anyway.  Also, the tooling can have functionality to  help find an instance type based on capacity requirements.

I think we should just use instance types in the CF and have the libs handle the interface to the user.

**Comment by ibaldin** [comment]
New flavors have been introduced.
