### ISSUE TITLE
Chameleon Example Fails

### ISSUE THREAD

**Issue by silvertenor** [fabric-testbed/jupyter-examples#196]
Hi, the chameleon stitching example fails when creating the fabric slice. The error message is here:

`Failure : Vlan for L2 service 3252 is outside the available range [3300, 3301, 3302, 3303, 3304, 3305, 3306, 3307, 3308, 3309]`

**Comment by kthare10** [comment]
The error message indicates that VLAN 3252 is in use and user should specify a different VLAN ID.
