### ISSUE TITLE
sudo hostname resolution fails after running nat64.sh

### ISSUE THREAD

**Issue by cunha** [fabric-testbed/jupyter-examples#240]
Running the `nat64.sh` script causes `sudo` to complain it cannot resolve the hostname (e.g., when calling `node.execute()`). It seems like removing `127.0.0.53` from the resolvers list causes this.

**Comment by kthare10** [comment]
FABRIC now hosts its own NAT Gateway and it is not required to use nat64.sh any more. So, closing the issue.
