### ISSUE TITLE
"First time using FABRIC" appears again when I login from firefox.

### ISSUE THREAD

**Issue by 842Mono** [fabric-testbed/jupyter-examples#26]
![image](https://user-images.githubusercontent.com/10537473/120075517-ed64b580-c0a1-11eb-81ee-bc012cdf56bf.png)

This dialogue is the one that appears when a user signs in to FABRIC for the first time. It popped up to me when I tried working from firefox.

**Comment by paul-ruth** [comment]
The portal/login has changed a lot since this version. I'm not sure this is repeatable anymore. Keep it in mind and look for it in the newer versions.

**Comment by 842Mono** [comment]
I tried Firefox one more time and it didn't happen :+1: I'll report if I ever catch it again.
