### ISSUE TITLE
When creating a new notebook with file-new and then save-as duplicates are created

### ISSUE THREAD

**Issue by nannkat** [fabric-testbed/jupyter-examples#28]
When I create a new jupyter notebook in the system without using the terminal and then do "save as" the following happens: instead of changing the name of the untitled notebook and saving it (like in most other editors) a new notebook with the correct name is created but the system also keeps a redundant untitled notebook.

**Comment by paul-ruth** [comment]
This is a jupyterhub issue. We can't do anything about it.
