### ISSUE TITLE
Copies of files from the main branch added to my Folders

### ISSUE THREAD

**Issue by TristanJordan99** [fabric-testbed/jupyter-examples#38]
![chrome_Od96LYkMyh](https://user-images.githubusercontent.com/35291790/120691374-608c7400-c474-11eb-89ee-13a3a6f64054.png)

Copies of files in the main branch were added to my folders, all timestamped with 20210602144303

**Comment by paul-ruth** [comment]
Is this still repeatable? This might have been a result of transitioning to the new portal/jupyter.  

If you can repeat this add instructions to do it here.
