### ISSUE TITLE
Can't delete non-empty folder.

### ISSUE THREAD

**Issue by nannkat** [fabric-testbed/jupyter-examples#41]
When I try to delete a non-empty folder in the environment the system throws an error, I have to manually delete all files within the folder beforehand for it to work. Which is tedious even with just two files...

https://user-images.githubusercontent.com/54936808/120731235-32795500-c4b1-11eb-89ac-5b5685aa61f7.mov

**Comment by nannkat** [comment]
And here I delete the files and then its ok to delete:

https://user-images.githubusercontent.com/54936808/120731323-5fc60300-c4b1-11eb-9243-31d33e11926f.mov

**Comment by paul-ruth** [comment]
This is more of an issues with jupyterhub. I don't think we can do anything about it.  It a bit of a linux limitation/backstop.  You can do this  from a bash shell either (at least not by default). 

There is a workaround. In a terminal try this:

#This should fail
rm /path/to/folder/that/is/not/empty

#This should work but us VERY POWERFUL and cannot be undone! Use with caution!
rm -r /path/to/folder/that/is/not/empty

**Comment by paul-ruth** [comment]
This is a jupyter interface issue.
