### ISSUE TITLE
Slice not configuring/ Slice status continuous loop

### ISSUE THREAD

**Issue by ninjajoe9** [fabric-testbed/jupyter-examples#43]
General Problem: Slice takes a very long time to configure/never configures 

Specific Problem: in simple-workshop-demo.ipynb, in the cell below 'Slice Status' a while loop runs until the 'slice_state' returns 'Stable OK'. Many times when I've run the cells in this notebook to test a base case this cell loops 
```
Response Status Status.OK
Slice State: Configuring
```
and either never stops 

<img width="849" alt="Screen Shot 2021-06-04 at 14 12 13" src="https://user-images.githubusercontent.com/48168373/120846854-b4fd2580-c540-11eb-8e02-982d1b8bfc25.png">

or errors with 
```
'ApiException' object has no attribute 'slice_state'
```
which it clearly did have in the preceding n-numebr of loops.

<img width="693" alt="Screen Shot 2021-06-02 at 11 44 33" src="https://user-images.githubusercontent.com/48168373/120846845-b0387180-c540-11eb-8c3d-2fde44443029.png">

(note: this second image is from a test slice I was working on the other day with similar code in the cell, NOT The 'simple-workship-demo.ipynb' notebook, but demonstrates the problem in another location.)

I don't know if this means the slice is failing to configure or if it's just stuck in the status and displaying incorrectly, but I can't test the slivers in the next cell or configure the nodes in subsequent cells until this cell completes and I don't know if interrupting it causes an erroneous failure when I run subsequent cells.

**Comment by abstractionAlpha** [comment]
For starters, change `slices[0].slice_state` to `slice_state`. This will use the version of the slice_state property we are updating instead of the value stored in the `slices` list -- which does not update until we run `status, slices = slice_manager.slices()` again. This is something we need to start doing in all of our notebooks.

Your slice does appear to be failing - which is an issue, but is a slightly different one. For now this update will help you get more accurate reporting on what is going on. Hope this helps.

**Comment by ninjajoe9** [comment]
I'm now encountering an additional interesting problem (I think not associated with the 'slices[0]' fix suggested in the previous comment) where halfway through 'configuring', the slice state all of a sudden switched to 'closing'. Subsequent runs of these cells now start as closing. Please see images below.  

problem:
<img width="730" alt="Screen Shot 2021-06-05 at 08 28 11" src="https://user-images.githubusercontent.com/48168373/120893281-79b23380-c5e0-11eb-86d4-08b5334cc856.png">

Additional runs:
<img width="702" alt="Screen Shot 2021-06-05 at 09 21 49" src="https://user-images.githubusercontent.com/48168373/120893282-7b7bf700-c5e0-11eb-88b3-f11a9c9d59e0.png">

**Comment by kthare10** [comment]
This is obsolete now. The new fablib interface takes care of polling for status and depicting. Slivers timeout after 30 minutes in case of any timeouts observed during provisioning and error information is passed to the user.
