### ISSUE TITLE
Need a way to know why slice creation failed.

### ISSUE THREAD

**Issue by 842Mono** [fabric-testbed/jupyter-examples#45]
When slice creation fails, we need a way to know what went wrong.

Below is the step by step process of how I know that the slice creation failed:

<hr/>

I try to create a slice.

`slice_manager.create(slice_name='JupyterSlice1', slice_graph=slice_graph, ssh_key=ssh_key)`

And then I query the slices using this:

`status, slices = slice_manager.slices()`

I run this line multiple times. I get "configuring" for some time.

```
Response Status Status.OK
Slices [{
    "graph_id": "aec118c8-41d0-42d0-a2d0-5857089a9695",
    "slice_id": "cb3d8d9c-ca02-44cf-8c13-9e8b15c97633",
    "slice_name": "JupyterSlice1",
    "slice_state": "Configuring"
}]
```
And then the slice disappears.

```
Response Status Status.OK
Slices []
```

I don't know what went wrong.

**Comment by paul-ruth** [comment]
duplicate
