### ISSUE TITLE
Include information about slice nodes when querying slices

### ISSUE THREAD

**Issue by nannkat** [fabric-testbed/jupyter-examples#55]
It would be a nice addition to get either the count of nodes for each slice or a list with the names of the nodes for that slice. So some form of a "nodes":  field.

<img width="562" alt="Screenshot 2021-06-11 at 14 42 19" src="https://user-images.githubusercontent.com/54936808/121734924-6cef7d00-cac3-11eb-9082-2583a7b9d23f.png">

**Comment by paul-ruth** [comment]
The idea is that "slices()" return a list of slices with the ids, name, and state. "slivers(slice_id=<ID>") returns the slivers for a slice. 

I think you are right that there is a need for a more complex call that gets the slice info and slivers for a specific slice.

Examples:
slice_man.slice(slice_name="NannaSlice")    --- Returns just "NannaSlice" but with all the slivers too.
slice_man.slices(slice_state="StableOK")    --- Returns a list of all "StableOK" slices.  "Error" and "Configuring" should be possible too.

All of these extra functions are easy to implement as wrappers around the other ones.  I wonder if we (i.e. the student group) wound be interested in implementing some of them.

**Comment by kthare10** [comment]
Fablib has been updated to return nodes/networks/interface information.
