### ISSUE TITLE
Need to get a descriptive error message when naming two links the same name.

### ISSUE THREAD

**Issue by 842Mono** [fabric-testbed/jupyter-examples#56]
We get an assertion error when naming two links the same name, but the error has no message.

![image](https://user-images.githubusercontent.com/10537473/121791941-77a73080-cbef-11eb-9b96-2a3e6af83e09.png)

![image](https://user-images.githubusercontent.com/10537473/121791929-5d6d5280-cbef-11eb-88af-0a43f789bcf8.png)

**Comment by kthare10** [comment]
Has been fixed and error indicating "Unique names should be used" is raised for such failures now.
