### ISSUE TITLE
Slice status vs. state

### ISSUE THREAD

**Issue by paul-ruth** [fabric-testbed/jupyter-examples#59]
The function slice_manager.slices() returns a list of slices.

The slices in the returned list have a field called "slice_state" which can be  "StableOK", "Configuring", etc.

However, the function that checks that field is:
slice_manager.slice_status(slice_id=slice_id)

I think we should be consistent and call it "status" or "state" but not use them interchangeable.

**Comment by kthare10** [comment]
slice_status api has been deprecated and removed. list_slices provided all the details for the slice.
