### ISSUE TITLE
It would be useful if we can see the available capacity hints (or instance sizes) from code.

### ISSUE THREAD

**Issue by 842Mono** [fabric-testbed/jupyter-examples#63]
I wasn't able to access [this file](https://github.com/fabric-testbed/InformationModel/blob/master/fim/slivers/data/instance_sizes.json) from code. It lists the possible capacity hints.

I imagine being able to do something like this:

    from fabrictestbed.slice_editor import CapacityHints, InstanceSizes
    print(InstanceSizes)

_Note that having both "InstanceSizes" and "CapacityHints" might be a bit confusing. Maybe something less confusing can be making a call to a function inside CapacityHints, like this:_

    CapacityHints.list_capacitiy_hints()

**Comment by nannkat** [comment]
Agree! a simple function that prints out the available choices would be very helpful

**Comment by kthare10** [comment]
We recommend users to specify cores/ram/disk needed. Mapping to flavors is done automatically by Control Framework
