### ISSUE TITLE
Might be useful to add the ability to reference slices by their name.

### ISSUE THREAD

**Issue by 842Mono** [fabric-testbed/jupyter-examples#64]
Feature request. Not very critical.

Right now, we can do things like:

    slice_manager.delete(slice_id=slice_id)

I think it would be useful to add the ability for us to do something like this:

    slice_manager.delete(slice_name=slice_name)

_The idea came from slice_manager.slices() being broken. I cannot query the slices that I have. And I get errors like `Slice JupyterSlice1 already exists`. I want to delete it, but I don't know its ID._

**Comment by kthare10** [comment]
Fablib API has been updated to provide support for slice_name/slice_id for all the APIs
