### ISSUE TITLE
Reservation state : 'unknown'

### ISSUE THREAD

**Issue by nannkat** [fabric-testbed/jupyter-examples#65]
I'm not sure if this is just something that has yet to be implemented, but currently I always get reservation state: 'unknown' when configuring a slice with slice_manager.create() and I find it uninformative.  It would be nice if the information printed from the 'reservations' object would be in a clear and organized format so the user also doesn't miss when the lease start/end period is. 

<img width="555" alt="reservation_state_unknown" src="https://user-images.githubusercontent.com/54936808/124621884-a27c5180-de48-11eb-89a7-04cdfbaefbbe.png">

**Comment by kthare10** [comment]
SliceManager is not used directly now by the user. Fablib API provides Sliver state as:

- Nascent
- Ticketed
- Active
- Failed
- Closed
