### ISSUE TITLE
Need a way to see the components attached to nodes or slivers.

### ISSUE THREAD

**Issue by 842Mono** [fabric-testbed/jupyter-examples#67]
I think that there's no way to know what components are attached to a node or a sliver.

I have a slice that was created previously. I want to determine what GPUs are attached to the nodes in the slice, but I don't know how.

_Things I tried:_

    slice_manager.slices()

    slice_manager.get_slice(slice_id="032be0ed-756b-46ef-8723-556361ece79f")

    slice_manager.slivers(slice_id="032be0ed-756b-46ef-8723-556361ece79f")

    slice_manager.sliver_status(slice_id="032be0ed-756b-46ef-8723-556361ece79f", sliver_id=s.reservation_id)

**Comment by 842Mono** [comment]
There doesn't seem to be a way to get the components of a slice that has already been created.

There is a way to get the components of a slice graph (which we use to issue a request), but there is no way to get the components of a slice that has already been created.

Example of the way to get components from a slice graph:

```
# Add node
n2 = t.add_node(name='n2', site='UKY')
# Set Properties
n2.set_properties(capacities=cap, image_type='qcow2', image_ref='default_ubuntu_20')
# Add PCI devices
n2.add_component(ctype=ComponentType.GPU, model='Tesla T4', name='gpu2')

print(n2.components)

c1 = n2.get_component("gpu2")
print(c1)
```

**Comment by kthare10** [comment]
Fablib API provides node.list_components()
