### ISSUE TITLE
(Feature Request) Let slice_manager.create() hold the output till it feeds the user back with success or failure.

### ISSUE THREAD

**Issue by 842Mono** [fabric-testbed/jupyter-examples#68]
This might be worth considering.

`slice_manager.create()` only issues the request. Might be a better idea for it to issue the request and also feed the user back with slice creation success or failure.

It seems that there's a loop that we do every time. We issue the request with `slice_manager.create()`. And then, we keep executing status commands like `slice_manager.slices()` or `slice_manager.slivers()` etc...

I think that it's more convenient for `slice_manager.create()` to keep capturing the output stream, till it feeds the user back with slice creation success or failure.

Another way to think of it is to incorporate something like script below into `slice_manager.create()`. The script below is the one that keeps waiting till the slice is ready. I've modified it to terminate if slice creation fails.

```
import time

slice_state=None
while slice_state != 'StableOK' and slice_state != 'Dead':
    status, slice_status = slice_manager.slice_status(slice_id=slice_id)
    slice_state = slice_status.slice_state
    print("Response Status {}".format(status))
    print("Slice State: {}".format(slice_state))
    time.sleep(20)

#status, slice_status = orchestrator_proxy.slice_status(token=fabric_id_token, slice_id=slice_id)

print("Response Status {}".format(status))
print("Slice Status {}".format(slice_status))
```

**Comment by paul-ruth** [comment]
argument to "wait" until Ok or Failed.

**Comment by kthare10** [comment]
This has been provided via Fablib API submit call.
