### ISSUE TITLE
Error when deleting slice that's already deleted

### ISSUE THREAD

**Issue by nannkat** [fabric-testbed/jupyter-examples#70]
When running a command to delete a slice, if the slice is already deleted the system throws an error. Of course it does not make sense to delete the same slice twice but I don't see the harm of the user being able to run the delete slices command without getting an error, at least not such a large one. In my opinion it would be more user friendly if there was a way to make this more 'quiet' so that it would not appear as an external error message but instead a command to be ignored in the background. 

<img width="1013" alt="error_when_deleting" src="https://user-images.githubusercontent.com/54936808/125343384-00ff6f00-e324-11eb-91f6-6f3d1f35e11f.png">

**Comment by paul-ruth** [comment]
I like the idea of making this (and all other) functions "quiet".  Maybe there could be two modes or a simple way to extract a simple error statement.

**Comment by kthare10** [comment]
Fablib API slice.delete() is quiet and doesn't throw error on deleting an already deleted slice.
