### ISSUE TITLE
Attribute interfaces not available

### ISSUE THREAD

**Issue by linjucs** [fabric-testbed/jupyter-examples#8]
In the "basic/slice.ipynb"
```
t.add_link(name='l1', interfaces=list(t.interfaces.values()), ltype=fu.LinkType.Wave)
```
```t.interfaces.values()``` should be replaced with ``` t.interface_list```

**Comment by feiatgithub** [comment]
Jupyter login issue:
The laptop (windows) and the browser (chrome) were freshly started. 
The homepage of the Beta site does require to login with my University credential. 
After clicking on Links (JupyterHub), it did not require login again, but the bar 
("Your server is startig up") did show up.

When I tried to run the python jupyter notebook (/jupyter-examples/fabric/basic/orchestrator.ipynb) 
the following error "Internal Server Error" appeared for cell [4], as shown in the following figure. 

One solution is: File -> Hub Control Panel -> Stop My Server -> Logout -> Sign in with CILogon. 

<img width="1063" alt="Internal_server_error" src="https://user-images.githubusercontent.com/42011426/115978705-5e6af780-a54f-11eb-809c-06262373c095.png">

**Comment by feiatgithub** [comment]
This is a test.

**Comment by paul-ruth** [comment]
This no longer applies or has been fixed.
