### ISSUE TITLE
Jupyter Notebook Login

### ISSUE THREAD

**Issue by feiatgithub** [fabric-testbed/jupyter-examples#9]
The laptop (windows) and the browser (chrome) were freshly started. 
The homepage of the Beta site does require to login with my University credential. 
After clicking on Links (JupyterHub), it did not require login again, but the bar 
("Your server is startig up") did show up.

When I tried to run the python jupyter notebook (/jupyter-examples/fabric/basic/orchestrator.ipynb) 
the following error "Internal Server Error" appeared for cell [4], as shown in the following figure. 

One solution is: File -> Hub Control Panel -> Stop My Server -> Logout -> Sign in with CILogon. 

Note: I am not sure whether it depends on how I shut down my laptop or exited my browser last time. 

<img width="1063" alt="Internal_server_error" src="https://user-images.githubusercontent.com/42011426/115978924-b81ff180-a550-11eb-9d2d-48264183b489.png">

**Comment by paul-ruth** [comment]
The token system has been updated and (I think) this error has been replaced with another. We should continue to look for errors like this but the system is different enough now that this error is outdated.
