### ISSUE TITLE
Impossible slivers

### ISSUE THREAD

**Issue by paul-ruth** [fabric-testbed/jupyter-examples#98]
There needs to be a way to figure out if a sliver is impossible. This could be a sliver that is never possible or just impossible right now.  

There are many combinations of components that are within the limits of the available resources at a site but are impossible. Usually this is because there are no hosts that have physically have some combination of components (i.e. a Tesla and an RX6000, but there are others).  However, more often this is an issue because a site is nearly full and there are only a few component left and they are all on different hosts.  In this case if should be possible to query the resources and figure out that it is currently impossible to have, for example, an ConnectX-6 and an NVMe on the same VM.   

This is independent of the problem that we can't guarantee that a request is possible because someone could have taken the resources in between your query and submitting the request.  If this were to happen you could re-query and confirm that there are no longer enough resources.  In the case of an impossible sliver that is within the resource availability limits there no way to figure out what type of slivers are actually possible.

**Comment by ibaldin** [comment]
We can add some rules - I was thinking about this and had a ticket for this fabric-testbed/InformationModel#57

**Comment by ibaldin** [comment]
The only issue is I can add that Orchestrator side. On the user side we don't have a rich query language.
