### ISSUE TITLE
PTP starts closed

### ISSUE THREAD

**Issue by TristanJordan99** [fabric-testbed/jupyter-examples#99]
When attempting to create a slice with a PTP connection the following is printed when requesting slivers:

![image](https://user-images.githubusercontent.com/35291790/133368450-e231d37b-8fc6-4da5-8d7d-eff2acab9eb0.png)

Note: L2PTP is closed

Slice creation:
![image](https://user-images.githubusercontent.com/35291790/133368645-207ce071-53e9-4f65-ad50-829217e84cbd.png)

**Comment by kthare10** [comment]
No longer an issue and can be verified via the notebook: https://github.com/fabric-testbed/jupyter-examples/blob/main/fabric_examples/fablib_api/create_l2network_basic_auto/create_l2network_basic_auto.ipynb
